spring:
  application:
    name: HospitalManagement

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Hospital
    username: postgres
    password: ${DB_PASSWORD:13102002}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    jwt:
      secret: hospital_management_jwt_secret_key_256_bits_long_secure


server:
  port: 8081


